### ISSUE TITLE
What do like about Ruby in comparison to other langues

### ISSUE THREAD

**Issue by M-Zuber** [benjmin-r/ama#2]
All languages have pluses and minuses.
What in your opinion are some of things that make Ruby shine?

**Comment by benjmin-r** [comment]
The people using and creating it 🙂

The culture around ruby, at least from what I've experienced from the outside over the years and from working with some people over last couple of months, is very straightforward and pragmatic. Most of the time, people want to get stuff done, and they just do it. This, plus (the impression) that the ruby community has, or tries to uphold, a certain aesthetic and usability when it comes to their code and tools (rspec being a prominent example), makes for a very pleasant experience. 

When it comes to the language itself, I don't see much that other modern languages do not offer too. Sure, blocks are very nice, and the ability to monkeypatch nearly all and everything makes for cool DSLs etc etc. But for me it's not why I would choose Ruby as a language.

Hope that answers your question 🙂
If not, I'm more than happy to answer further questions, if you have any 😃
