### ISSUE TITLE
what would it take to part with your twitter handle?

### ISSUE THREAD

**Issue by benjaminhoffman** [benjmin-r/ama#4]
i'd love to have your twitter handle and curious if you'd be open to parting with it?  

ps.  love this idea of an AMA.  super clever.

**Comment by benjmin-r** [comment]
No, I'm not parting with my twitter handle 🙂

And thanks for the compliment. I didn't come up with the idea for an AMA myself, but rather seen a lot of other people do it and then saw [Sindre's repo](https://github.com/sindresorhus/amas).
